// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGRrtnyY-u8amp70UbwVssGv6EefUSY8',
    appId: '1:4142093377:web:8965c001253d7ef46fa2c0',
    messagingSenderId: '4142093377',
    projectId: 'koko-restaurant',
    authDomain: 'koko-restaurant.firebaseapp.com',
    storageBucket: 'koko-restaurant.firebasestorage.app',
    measurementId: 'G-H2LQL0PNZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRsOq5sAaGJPjtwQWnQ2DQwQJnlCFd41g',
    appId: '1:4142093377:android:67926ee9b8d19f0b6fa2c0',
    messagingSenderId: '4142093377',
    projectId: 'koko-restaurant',
    storageBucket: 'koko-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYt-LkSIuL5kf8aHTCqdHDr7Ok2gqmp8Y',
    appId: '1:4142093377:ios:a229f9f985bd66856fa2c0',
    messagingSenderId: '4142093377',
    projectId: 'koko-restaurant',
    storageBucket: 'koko-restaurant.firebasestorage.app',
    iosBundleId: 'com.zonafood.kokoplaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYt-LkSIuL5kf8aHTCqdHDr7Ok2gqmp8Y',
    appId: '1:4142093377:ios:a229f9f985bd66856fa2c0',
    messagingSenderId: '4142093377',
    projectId: 'koko-restaurant',
    storageBucket: 'koko-restaurant.firebasestorage.app',
    iosBundleId: 'com.zonafood.kokoplaza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMGRrtnyY-u8amp70UbwVssGv6EefUSY8',
    appId: '1:4142093377:web:dca0fd2a6437ea186fa2c0',
    messagingSenderId: '4142093377',
    projectId: 'koko-restaurant',
    authDomain: 'koko-restaurant.firebaseapp.com',
    storageBucket: 'koko-restaurant.firebasestorage.app',
    measurementId: 'G-2YRV2B8G4J',
  );
}
